pec1 = input()
pec2 = input()
A, B, C = pec1.split(" ")
A = int(A)
B = int(B)
C = float(C)
D, E, F = pec2.split(" ")
D = int(D)
E = int(E)
F = float(F)
print("VALOR A PAGAR: R$ {:.2f}".format((B*C)+(E*F)))
